{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "midnight-core.fullname" . }}-ingress
  labels:
    {{- include "midnight-core.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.domainName }}
      secretName: {{ .Values.ingress.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: {{ include "midnight-core.fullname" . }}-owl-api
                port:
                  number: {{ .Values.owlApi.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "midnight-core.fullname" . }}-lark-ui
                port:
                  number: {{ .Values.larkUi.service.port }}
{{- end }}
