appVersion: "latest"
domainName: patchbay.example.com

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

imagePullSecrets: []

imageCredentials:
  enabled: false
  registry: ""
  username: ""
  password: ""
  email: ""

forceRedeploy: false

# #########################################################
# patchbay-backend service (Backend API)
# #########################################################
patchbayBackend:
  replicaCount: 1

  image:
    repository: ghcr.io/hackclub/patchbay/patchbay-backend
    pullPolicy: IfNotPresent
    tag: "latest"

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 3000

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  env:
    NODE_ENV: "production"
    PORT: "3000"

  secretEnv: {}

  extraEnvVars: []

  externalConfigMapName: ""
  externalSecretName: ""

# #########################################################
# patchbay-frontend service (Frontend UI)
# #########################################################
patchbayFrontend:
  replicaCount: 1

  image:
    repository: ghcr.io/hackclub/patchbay/patchbay-frontend
    pullPolicy: IfNotPresent
    tag: "latest"

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 8080

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  env:
    NODE_ENV: "production"
    PORT: "8080"

  secretEnv: {}

  extraEnvVars: []

  externalConfigMapName: ""
  externalSecretName: ""

# #########################################################
# ingress configuration
# #########################################################
ingress:
  enabled: true
  className: "traefik"
  tls: true
  secretName: "patchbay-cert"
  pathType: ImplementationSpecific

  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web

  # Gateway middleware for routing
  gatewayMiddleware:
    enabled: true
